### ISSUE TITLE
interactive map doesn't work

### ISSUE THREAD

**Issue by KJSanchez** [odubno/NYC311Project#2]
Cool app! I'd like to use it but the interactive map doesn't seem to work? The map never renders. 

https://odubno.shinyapps.io/nyc311app/

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/40d8e764-b1d8-4b0d-ab38-793f9fc1bd8b">

**Comment by odubno** [comment]
you have to make a selection for it to render. i.e. since there's no data selected on the left, there's nothing to render
